name: Docx Change Track by Transfer to Html

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: track up docx change
        run: |
          python transfer.py
      
      - name: Get current date
        id: datetime
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit
        env:
          $USER_EMAIL: ${{ secrets.USER_EMAIL }}
          $USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "feat: track change ${{ steps.datetime.outputs.date }}" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets._GITHUB_TOKEN }}